### ISSUE TITLE
Maintainer of Project

### ISSUE THREAD

**Issue by larryg01** [gkushang/cucumber-html-reporter#265]
@gkushang 

Nothing has been done with this project for a year and I uses it.
It would be great if you give me control of the project so it can be maintained

What is your process as you are not maintaining it anymore?
I would be happy to take control of the project?

This is not just to have the ability to do merges and bug fixes but the the entire project and bring it up to date
Let me know you thoughts.

**Comment by gkushang** [comment]
@larryg01  - thanks for your interest in contributing and maintaining along side. I have sent you the invite. Let me know if you have all the access.

**Comment by larryg01** [comment]
@gkushang This is my first time as a maintainer to a project besides my own, from what I can see I think I have all the access thats needed

**Comment by larryg01** [comment]
Hi @gkushang

We have upgraded the project on github and would like to get permission to publish it to NPM
Can this be arrange please or can you pull the code and do the publish as i don't have access to post to NPM

**Comment by gkushang** [comment]
@larryg01  - would you like to be part of Publishing Mantainer on NPM? if so, can you provide your NPM ID?

**Comment by gkushang** [comment]
done, I published the V5.5.1

**Comment by larryg01** [comment]
I have to admit this should have been published as v6.0.0 because it was a major upgrade doing it as v5.5.1 suggest that it was just a minor change. Hence the reason I made a v6 build in github and its even set in the package.json as v6.0.0 so at the moment it will be downloaded as v5.5.1 and all the docs etc saying v6.0.0

**Comment by larryg01** [comment]
Yes I would like to be a part of the Publishing Maintainer on NPM.My username is the same as my github id  ‘Larryg01’ Thanks and RegardsLarryG https://btaawards.com/2023-finalists/#developer Larry Goddard | Test Automation ***@***.*** T: https://twitter.com/LarryG_01L: https://linkedin.com/in/larryg/Y: ***@***.***_01  From: Kushang Gajjar ***@***.***>Date: Tuesday, 14 March 2023 at 00:00To: gkushang/cucumber-html-reporter ***@***.***>Cc: LarryG ***@***.***>, Mention ***@***.***>Subject: Re: [gkushang/cucumber-html-reporter] Maintainer of Project (Issue ***@***.*** - would you like to be part of Publishing Mantainer on NPM? if so, can you provide your NPM ID?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by gkushang** [comment]
@larryg01 - done, released as a major version V6.0.0!

**Comment by larryg01** [comment]
Sorry clicked the wrong button:
If you missed this, you asked if i would like to be part fo the publishing team:

Yes I would like to be a part of the Publishing Maintainer on NPM.
My username is the same as my github id  ‘Larryg01’ 

Thanks and Regards

LarryG

**Comment by larryg01** [comment]
@gkushang  I just realised that you rolled back all the dependencies version pre-upgrade
If thats the case then the v6.0.0 is not v6.0.0 as per my upgrade.
thats just crazy as anyone pulling v6.0.0 is not getting the true code
